# Generated by Django 4.2.10 on 2024-02-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                default="profile_images/default.jpg", upload_to="profile_images/"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="resume",
            field=models.FileField(default="resumes/default.pdf", upload_to="resumes/"),
        ),
    ]
