# Generated by Django 4.2.10 on 2024-03-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_resume_original_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="original_image_file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="original_resume_file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
