# Generated by Django 4.2.10 on 2024-03-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_profile_degree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="institution_name_enum",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
